language: objective-c
branches:
  only:
  - master
xcode_project: RateMyMeetings.xcodeproj
script: xctool -scheme RateMyMeetings test
env:
  global:
    - APP_NAME="RateMyMeetings"
    - 'DEVELOPER_NAME="iPhone Distribution: {iOS Developer}"'
    - PROFILE_NAME="iOS_Team_Provisioning_Profile_"
    secure: bavp+4YeH9W7Ecoi2gbpwcEaeR+PczcW5OYzZgQFtqzp3hkHAkTTxIqIMtbca4M/ANcPQXsf0/m+u7iaSXdjvZOfofohfWeInQr9zFkLvMk+SOZEGxJMLZB4ih9EJrDB4rmuvWeNrXGifAAKTL34GXutzB5XnQHtcwZiu5o/CBecEg2yDdpnpl2iHivc0eLvSUNvpAiW7lX8UI36tneB2MqzGyybPbMLSpLt20rKj3aqyUrj8SSWM3vSVutL4ilkUspZtwRA0xEdH04C2V5w1JIZLk/FYPzWYCJft9jn508fYK0bGDAGPPgbgolxPL0C4Qp052c+bHH4NuM6nvKIyHnqPdTpifg4aUFVpYh9dcwSiwUlljreEKu++zhm2Q4g0qOEeCrsGcs4+rebKx6Xkl/kJLKpxlLkeeaM16Dt1kbJIvbbm0nGwsFmzsLd49APYeMPuy9+KyfrIptq985qJpc2cl30eZ3u1r04SUk62hyfjtfq1JAel2y6DlJms4+3200CD+zUQYW+QoNw7m2N/87vGwSfoZbwJglUfg7pzj8qMnZNWDfzywehrsWpkEoeLLD4hZ9YSGDhcSO875iQb6O2PkfcDv7pw1BPK+D3jyd+IkgGiLIWSHRQpLyiNl9dyUZqkd9npKvTqcSL6nGUeC2/6QbzHd/xQmVdLt0Qenw=
